name: Windows

on: 
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Build
      run: .\build.cmd
